export enum ZType {
  Any = 'ZAny',
  Array = 'ZArray',
  BigInt = 'ZBigInt',
  Boolean = 'ZBoolean',
  Date = 'ZDate',
  Enum = 'ZEnum',
  False = 'ZFalse',
  Function = 'ZFunction',
  Intersection = 'ZIntersection',
  Literal = 'ZLiteral',
  NaN = 'ZNaN',
  Never = 'ZNever',
  Null = 'ZNull',
  Nullable = 'ZNullable',
  Nullish = 'ZNullish',
  Number = 'ZNumber',
  Object = 'ZObject',
  Optional = 'ZOptional',
  String = 'ZString',
  True = 'ZTrue',
  Tuple = 'ZTuple',
  Undefined = 'ZUndefined',
  Union = 'ZUnion',
  Unknown = 'ZUnknown',
  Void = 'ZVoid',
}
